openapi: 3.0.3
info:
  title: Hylo Travel AI - Build Validation API
  version: 1.0.0
  description: API contracts for build and deployment validation

servers:
  - url: https://hylo-travel-ai.vercel.app/api
    description: Production server

paths:
  /api/health:
    get:
      summary: Health check endpoint for deployment validation
      operationId: getHealthStatus
      responses:
        '200':
          description: Service is healthy and deployment successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [healthy]
                  timestamp:
                    type: string
                    format: date-time
                  version:
                    type: string
                  functions:
                    type: object
                    properties:
                      count:
                        type: integer
                        maximum: 12
                      list:
                        type: array
                        items:
                          type: string
                    required:
                      - count
                required:
                  - status
                  - timestamp
                  - version
                  - functions

components:
  schemas:
    BuildStatus:
      type: object
      properties:
        typescript:
          type: object
          properties:
            compiled:
              type: boolean
            errors:
              type: integer
              minimum: 0
          required:
            - compiled
            - errors
        functions:
          type: object
          properties:
            count:
              type: integer
              maximum: 12
            valid:
              type: boolean
          required:
            - count
            - valid
      required:
        - typescript
        - functions
